# Generated by Django 6.0.1 on 2026-02-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📦', max_length=50)),
                ('color', models.CharField(default='#FF6B00', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=100)),
                ('marketplace_url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('count_offers', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partners.category')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['order'],
            },
        ),
    ]
