# Generated by Django 6.0.1 on 2026-02-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='partner_category',
        ),
    ]
