# Generated by Django 6.0.1 on 2026-02-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
