# Generated by Django 6.0.1 on 2026-02-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_product_short_description_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
